version: '3.1'

services:

  service1:
    image: microservice-service1:1
    container_name: service1
    ports:
      - 10000:80
    environment:
      - "SPRING_PROFILES_ACTIVE=kub"

  service2:
    image: microservice-service2:1
    container_name: service2
    ports:
      - 11000:80
    environment:
      - "SPRING_PROFILES_ACTIVE=kub"
